### ISSUE TITLE
Data type "tinyint" is not supported by postgres

### ISSUE THREAD

**Issue by CarlosFandango** [kultprosvet/obrigado-react-admin-backend-utils#2]
# Issue

Postgres is a popular choice of database and unfortunately the mirgration for `Administrators.isBlocked` is storing the boolean of `isBlocked` as a TinyInt which is not compatible with Postgres.

### Error raised on migration

(node:77004) UnhandledPromiseRejectionWarning: DataTypeNotSupportedError: Data type "tinyint" in "Administrator.isBlocked" is not supported by "postgres" database.

### Cause

https://github.com/kultprosvet/obrigado-react-admin-backend-utils/blob/504b776e820b7c3cd60b919af00a761d4708abe3/src/migrations/1566135243910-AddIsBlocked.ts#L8

```
new TableColumn({
        name: "isBlocked",
        type: "tinyint", // <---- Here, tinyint is specified to represent the boolean.
        isNullable: false,
        default: 0
      })
```

### Suggested Solution

Change `isBlocked` to a `boolean`. As tinyint is a synonym of a Boolean type, this would be a superficial change for most databases, but would fix the issue for PostgreSQL.

```
new TableColumn({
        name: "isBlocked",
        type: "boolean",
        isNullable: false,
        default: 0
      })
```

**Comment by volnyansky** [comment]
@CarlosFandango Thanks for your report. I refactored all migrations to support postgres.

v1.3.8

**Comment by CarlosFandango** [comment]
Thanks @volnyansky. Is this in a branch I can test?
When do you think you will be releasing that refactoring?

**Comment by volnyansky** [comment]
@CarlosFandango Yes. There is only a master branch yet. You can test it now, also I've published v1.3.8 with the latest changes of this lib to npm.

**Comment by CarlosFandango** [comment]
Sorry @volnyansky, I'm not seeing any changes to master other than the readme merge and 1.3.8 is still having this problem on Postgres.

`Data type "tinyint" in "Administrator.isBlocked" is not supported by "postgres" database.`
